# Site settings
title: Ali Sina
email:
description: > # this means to ignore newlines until "baseurl:"
  Finance major, but love coding and programming. Here I share stuff that
  interests me, but mostly about coding, machine learning, and data analysis.
  Currently living in China.
baseurl: "/"
url: "https://alisiina.github.io"
author: Ali Sina
github_username:  alisiina


# Social media linke for jekyll-seo-tag
social:
 name: Ali Sina
 links:
  - https://github.com/alisiina
  - https://linkedin/in/alisina


# Build settings
markdown: kramdown
highlighter: rouge # But these styles are overridden?


# Markdown Processors (defaults)
#rdiscount:
#  extensions        : []

#redcarpet:
#  extensions        : []


# Pagination settings
paginate: 5
paginate_path: "/posts/page:num"


# Plugins
plugins:
 - jekyll-paginate
 - jekyll-seo-tag
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
