title: Ali Sina's Page
email:
description: > # this means to ignore newlines until "baseurl:"
  Hey there! My name is Ali! Finance major. Coding enthusiast. Lives in China.
baseurl: "/"
url: "https://alisiina.github.io"
author: Ali Sina
github_username:  alisiina

social:
  name: Ali Sina
  links:
    - https://github.com/alisiina
    - https://linkedin/in/alisina



# Build settings
markdown: kramdown
syntax_highlighter: rouge


# Pagination settings
paginate: 5
paginate_path: "/posts/page:num"


plugins:
  - jekyll-paginate
  - jekyll-seo-tag
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
